# -*- coding: utf-8 -*-
"""Proyek Akhir Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxyIbv4mwajnT6F6Cjbye_dXNpmwR5GJ

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [Rahmat Dwi Putra]
- **Email:** [rahmatgt21@gmail.com]
- **ID Dicoding:** [rahmat_dwi_putra_21]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Bagaimana pola penggunaan sepeda pada hari kerja dan akhir pekan?
- Pertanyaan 2 : Bagaimana pengaruh cuaca terhadap penggunaan sepeda?

## Import Semua Packages/Library yang Digunakan
"""

!pip install streamlit
!pip install pyngrok

# mengimport library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# membaca dataset
day_data = pd.read_csv("/content/drive/MyDrive/Bangkit Academy 2024 By Google, GoTo, Tokopedia, Traveloka - Machine Learning Path /day.csv")
hour_data = pd.read_csv("/content/drive/MyDrive/Bangkit Academy 2024 By Google, GoTo, Tokopedia, Traveloka - Machine Learning Path /hour.csv")
#menampilkan baris pertama dari dataset
print(day_data.head())
print(hour_data.head())

# cek apa ada data yang missing values di dataset
print(day_data.isnull().sum())
print(hour_data.isnull().sum())

# ini cek tipe data
print(day_data.dtypes)
print(hour_data.dtypes)

#kalo perlu ubah tipe data
day_data['dteday'] = pd.to_datetime(day_data['dteday'])

# membuat kolom baru untuk mengelompokan hari kerja dan akhir pekan
day_data['is_weekend'] = day_data['weekday'].apply(lambda x: 1 if x >= 5 else 0)

# visual pola pengguna sepeda berdasarkan akhir pekan dan hari kerja
plt.figure(figsize=(10, 6))
sns.barplot( data=day_data, x='is_weekend', y='cnt', estimator=np.mean, errorbar=None)
plt.title('Rata-rata Pengunjung sepeda berdasarkan hari kerja dan akhir pekan')
plt.xlabel('Akhir Pekan (1: Ya, 0: Tidak)')
plt.ylabel('Rata-rata Pengunjung')
plt.show()

# visual cuaca terhadap pengguna sepeda
plt.figure(figsize=(10, 6))
sns.barplot(data=day_data, x='weathersit', y='cnt')
plt.title('Rata-rata Pengunjung sepeda berdasarkan cuaca')
plt.xlabel('Kondisi Cuaca')
plt.ylabel('Rata-rata Pengunjung')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# # Judul Dashboard
# st.title('Dashboard Pengguna Sepeda')
# 
# # Membuat dataset
# day_data = pd.read_csv('/content/drive/MyDrive/Bangkit Academy 2024 By Google, GoTo, Tokopedia, Traveloka - Machine Learning Path /day.csv')
# hour_data = pd.read_csv('/content/drive/MyDrive/Bangkit Academy 2024 By Google, GoTo, Tokopedia, Traveloka - Machine Learning Path /hour.csv')
# 
# # menampilkan data
# st.write('Tabel Data Pengguna Sepeda')
# st.write(day_data.head())
# 
# # visual 1: Penggunaan sepeda di akhir pekan dan hari kerja
# st.write('Visualisasi Penggunaan Sepeda di Akhir Pekan dan Hari Kerja')
# day_data['is_weekend'] = day_data['weekday'].apply(lambda x: 1 if x >= 5 else 0)
# fig, ax = plt.subplots()
# sns.barplot(data=day_data, x='is_weekend', y='cnt', estimator=np.mean, ax=ax)
# st.pyplot(fig)
# 
# # visual 2 : Pengaruh cuaca terhadap penggunaan sepeda
# st.write('Visualisasi Pengaruh Cuaca terhadap Penggunaan Sepeda')
# fig, ax = plt.subplots()
# sns.barplot(data=day_data, x='weathersit', y='cnt', ax=ax)
# st.pyplot(fig)

from pyngrok import ngrok

# jalankan streamlit
!streamlit run app.py & npx localtunnel --port 8501

# url ngrok
#public_url = ngrok.connect(port='8501')
#print(f"Dashboard Streamlit tersedia di: {public_url}")